/* Automatically generated by './build/bin/build-entry.js' */

import Alert from '../packages/alert/index.js';
import Button from '../packages/button/index.js';
import Icon from '../packages/icon/index.js';
import Scrollbar from '../packages/scrollbar/index.js';
import Row from '../packages/row/index.js';
import Col from '../packages/col/index.js';
import Progress from '../packages/progress/index.js';
import Loading from '../packages/loading/index.js';
import Tabs from '../packages/tabs/index.js';
import TabPane from '../packages/tabPane/index.js';
import Breadcrumb from '../packages/breadcrumb/index.js';
import BreadcrumbItem from '../packages/breadcrumbItem/index.js';
import Link from '../packages/link/index.js';
import Tag from '../packages/tag/index.js';
import Switch from '../packages/switch/index.js';
import Notification from '../packages/notification/index.js';
import Message from '../packages/message/index.js';
import MessageBox from '../packages/message-box/index.js';
import Form from '../packages/form/index.js';
import FormItem from '../packages/form-item/index.js';
import Input from '../packages/input/index.js';
import DatePicker from '../packages/date-picker/index.js';
import Slider from '../packages/slider/index.js';
import Checkbox from '../packages/checkbox/index.js';
import CheckboxGroup from '../packages/checkbox-group/index.js';
import Radio from '../packages/radio/index.js';
import RadioGroup from '../packages/radio-group/index.js';
import RadioButton from '../packages/radio-button/index.js';
import Option from '../packages/option/index.js';
import OptionGroup from '../packages/option-group/index.js';
import Select from '../packages/select/index.js';
import Collapse from '../packages/collapse/index.js';
import CollapseItem from '../packages/collapse-item/index.js';
import Backtop from '../packages/backtop/index.js';
import Carousel from '../packages/carousel/index.js';
import CarouselItem from '../packages/carousel-item/index.js';
import Skeleton from '../packages/skeleton/index.js';
import SkeletonItem from '../packages/skeleton-item/index.js';
import Card from '../packages/card/index.js';
import Container from '../packages/container/index.js';
import Header from '../packages/header/index.js';
import Footer from '../packages/footer/index.js';
import Aside from '../packages/aside/index.js';
import Main from '../packages/main/index.js';
import Dialog from '../packages/dialog/index.js';
import Upload from '../packages/upload/index.js';
import Cascader from '../packages/cascader/index.js';
import Transfer from '../packages/transfer/index.js';
import Pagination from '../packages/pagination/index.js';
import Tree from '../packages/tree/index.js';
import Drawer from '../packages/drawer/index.js';
import Rate from '../packages/rate/index.js';
import Badge from '../packages/badge/index.js';
import Tooltip from '../packages/tooltip/index.js';
import Popover from '../packages/popover/index.js';
import InfiniteScroll from '../packages/infinite-scroll/index.js';
import Table from '../packages/table/index.js';
import PageHeader from '../packages/page-header/index.js';
import TableColumn from '../packages/table-column/index.js';
import Steps from '../packages/steps/index.js';
import Step from '../packages/step/index.js';
import locale from 'wlkj-ui/src/locale';
import CollapseTransition from 'wlkj-ui/src/transitions/collapse-transition';

const components = [
  Alert,
  Button,
  Icon,
  Scrollbar,
  Row,
  Col,
  Progress,
  Tabs,
  TabPane,
  Breadcrumb,
  BreadcrumbItem,
  Link,
  Tag,
  Switch,
  Form,
  FormItem,
  Input,
  DatePicker,
  Slider,
  Checkbox,
  CheckboxGroup,
  Radio,
  RadioGroup,
  RadioButton,
  Option,
  OptionGroup,
  Select,
  Collapse,
  CollapseItem,
  Backtop,
  Carousel,
  CarouselItem,
  Skeleton,
  SkeletonItem,
  Card,
  Container,
  Header,
  Footer,
  Aside,
  Main,
  Dialog,
  Upload,
  Cascader,
  Transfer,
  Pagination,
  Tree,
  Drawer,
  Rate,
  Badge,
  Tooltip,
  Popover,
  Table,
  PageHeader,
  TableColumn,
  Steps,
  Step,
  CollapseTransition
];

const install = function(Vue, opts = {}) {
  locale.use(opts.locale);
  locale.i18n(opts.i18n);

  components.forEach(component => {
    Vue.component(component.name, component);
  });

  Vue.use(InfiniteScroll);
  Vue.use(Loading.directive);

  Vue.prototype.$WLKJ = {
    size: opts.size || '',
    zIndex: opts.zIndex || 2000
  };

  Vue.use(Loading.directive);
  Vue.prototype.$loading = Loading.service;
  Vue.prototype.$notify = Notification;
  Vue.prototype.$message = Message;
  Vue.prototype.$msgbox = MessageBox;
  Vue.prototype.$alert = MessageBox.alert;
  Vue.prototype.$confirm = MessageBox.confirm;
  Vue.prototype.$prompt = MessageBox.prompt;
};

/* istanbul ignore if */
if (typeof window !== 'undefined' && window.Vue) {
  install(window.Vue);
}

export default {
  version: '0.0.1',
  locale: locale.use,
  i18n: locale.i18n,
  install,
  CollapseTransition,
  Loading,
  Alert,
  Button,
  Icon,
  Scrollbar,
  Row,
  Col,
  Progress,
  Tabs,
  TabPane,
  Breadcrumb,
  BreadcrumbItem,
  Link,
  Tag,
  Switch,
  Notification,
  Message,
  MessageBox,
  Form,
  FormItem,
  Input,
  DatePicker,
  Slider,
  Checkbox,
  CheckboxGroup,
  Radio,
  RadioGroup,
  RadioButton,
  Option,
  OptionGroup,
  Select,
  Collapse,
  CollapseItem,
  Backtop,
  Carousel,
  CarouselItem,
  Skeleton,
  SkeletonItem,
  Card,
  Container,
  Header,
  Footer,
  Aside,
  Main,
  Dialog,
  Upload,
  Cascader,
  Transfer,
  Pagination,
  Tree,
  Drawer,
  Rate,
  Badge,
  Tooltip,
  Popover,
  InfiniteScroll,
  Table,
  PageHeader,
  TableColumn,
  Steps,
  Step
};
